### ISSUE TITLE
qoverview-config-server: crashed TypeError: Can't mix strings and bytes

### ISSUE THREAD

**Issue by slackernetuk** [bharadwaj-raju/qOverview#15]
I have some qoverview-config-server issues, 

**MySystem**
Slackware
Kernel 5.4.70 
Xfce 4.16pre1

**Slackware dependencies**

python3-3.8.6
PyQt5-5.15.1
dbus-python-1.2.16
pygobject3-3.36.1
python3-PyYAML-3.13
xdotool-3.20160805.1
wmctrl-1.07

I've installed qOverview without KDE framework.

```
lancs@darkstar ~ $ qoverview-config-server
Traceback (most recent call last):
  File "/usr/bin/qoverview-config-server", line 428, in <module>
    info = _get_desktop_entry_info(desktop_entry_loc)
  File "/usr/bin/qoverview-config-server", line 330, in _get_desktop_entry_info
    info['IconPath'] = _get_icon(info.get('Icon', ''))
  File "/usr/bin/qoverview-config-server", line 377, in _get_icon
    if os.path.exists(os.path.join(path, theme, cat, size, icon_name + ext)):
  File "/usr/lib64/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.8/genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

**Comment by bharadwaj-raju** [comment]
This repo is dead. Report the issue at https://gitlab.com/bharadwaj-raju/qOverview please.
