### ISSUE TITLE
qoverview-config-server execution error/python TypeError 

### ISSUE THREAD

**Issue by jennydaman** [bharadwaj-raju/qOverview#4]
Hi it's me again.
This project really excited me, as GNOME overview is so beautiful but GNOME itself is so slow... the design of this project seems to be the most alike GNOME overview. (xfdashboard is too much like unity)

But there are still some issues that I had with qoverview-config-server.

My system: 
Arch Linux (zen kernel) 
XFCE4
Python 3.6.1

after git pull && sudo ./install.sh, I tried running qoverview-config-server. My mouse turned into a plus shape, and I couldn't click anything. 
I broke out of this bug by double clicking (really fast, maybe it triggers an action). qoverview-config-server could crash with the following output: 
```
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9182.
/usr/bin/qoverview-config-server: line 4: from: command not found
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9182.
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9182.
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9182.
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9182.
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9182.
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9182.
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9182.
/usr/bin/qoverview-config-server: line 13: from: command not found
/usr/bin/qoverview-config-server: line 15: syntax error near unexpected token `('
/usr/bin/qoverview-config-server: line 15: `config_dir = os.environ.get('XDG_CONFIG_DIR', os.path.expanduser('~/.config'))'
```
This is likely because qoverview-server is not being interpreted as python. 
I tried python3 /usr/bin/qoverview-config-server
```
Traceback (most recent call last):
  File "/usr/bin/qoverview-config-server", line 426, in <module>
    info = _get_desktop_entry_info(_desktop_entry_locate(entry))
  File "/usr/bin/qoverview-config-server", line 329, in _get_desktop_entry_info
    info['IconPath'] = _get_icon(info.get('Icon', ''))
  File "/usr/bin/qoverview-config-server", line 378, in _get_icon
    if os.path.exists(os.path.join(path, theme, cat, size, icon_name + ext)):
  File "/usr/lib/python3.6/posixpath.py", line 92, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.6/genericpath.py", line 151, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

**Comment by bharadwaj-raju** [comment]
The time that `qoverview-config-server` was run as bash, it overwrote a few important files probably.

Install again and see. (Also: edit the config-server.py file to have a line `#!/usr/bin/env python3` at the top before running `install.sh`).

**Comment by bharadwaj-raju** [comment]
Closing for now, but it may be some other issue.
