### ISSUE TITLE
KDE Neon does not work (details inside)

### ISSUE THREAD

**Issue by stratus-ss** [bharadwaj-raju/qOverview#8]
Hi,

OS info:
```
DISTRIB_ID=neon
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="KDE neon User Edition 5.12"
NAME="KDE neon"
VERSION="5.12"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User Edition 5.12"
VERSION_ID="16.04"
HOME_URL="http://neon.kde.org/"
SUPPORT_URL="http://neon.kde.org/"
BUG_REPORT_URL="http://bugs.kde.org/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

I tried to follow the directions on your page to install. The install output:

```
~/temp/qOverview$ sudo ./install.sh 
/home/<user>
Installing...
Enabling use of KDE Frameworks...
Patching ui.qml...
Patching qoverview.py...
```

However trying to run it produces:
```
Application (desktop entry) display-im6.distrib not found
Traceback (most recent call last):
  File "/usr/bin/qoverview-config-server", line 425, in <module>
    info = _get_desktop_entry_info(_desktop_entry_locate(entry))
  File "/usr/bin/qoverview-config-server", line 317, in _get_desktop_entry_info
    with open(desktop_file_path) as f:
TypeError: invalid file: None
```
It appears to originate from the fact that /usr/share/applications has several <application name>.distrib files. I inserted this on line 425

```
for entry in desktop_entries:
        if "distrib" in entry:
                continue
```

This allowed the overview to launch:

```
~/temp/qOverview$ sudo qoverview-config-server 
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for mark-location-symbolic; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for utilities-terminal; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for printer; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for printer; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for plasma; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for knetattach; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for printer; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for preferences-system; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for utilities-system-monitor; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for utilities-terminal; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for plasma; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for preferences-system-bluetooth; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for preferences-system; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for system-file-manager; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for applications-other; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for tools-report-bug; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for preferences-desktop-color; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for kwrite; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for gnome-mpv; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for obs; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for klipper; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for preferences-system-bluetooth; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for utilities-system-monitor; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
No icon found for hwinfo; falling back to missing-icon.svg
Cannot detect system icon theme; falling back to hicolor. Try setting an icon theme in the settings.
```

When I try to use xdotool I get the following error:
```
 xdotool behave_screen_edge top-left exec qoverview  File "/usr/bin/qoverview", line 87
    print(f'Switching to workspace: {num}')
                                         ^
SyntaxError: invalid syntax
  File "/usr/bin/qoverview", line 87
    print(f'Switching to workspace: {num}')
```

I get the same error when just running `qoverview`

If I can provide more info let me know!

**Comment by bharadwaj-raju** [comment]
Thanks for the report. qOverview not working on the flagship KDE distro is a huge bug indeed.

Both the errors have easy fixes, but unfortunately I'll only be able to upload the fixes on Friday evening (IST). Sorry for the delay.

**Comment by bharadwaj-raju** [comment]
Thanks for the report. Fixed.

**Comment by stratus-ss** [comment]
I have run into another issue:

```
~/temp/qOverview$ git pull -r
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/bharadwaj-raju/qOverview
   df91206..2cf8cf8  master     -> origin/master
First, rewinding head to replay your work on top of it...
Fast-forwarded master to 2cf8cf8ac58f5a48fbbc9869a6042ca593ae549c

~/temp/qOverview$ sudo ./install.sh 
/home/sovens
Installing...
Enabling use of KDE Frameworks...
Patching ui.qml...
Patching qoverview.py...

~/temp/qOverview$ qoverview-config-server 
Traceback (most recent call last):
  File "/usr/bin/qoverview-config-server", line 427, in <module>
    info['EntryName'] = entry
NameError: name 'info' is not defined
```
